Assets/Prefabs/SceneSelectionPanel.prefab, Assets/Scenes/Horizon.unity, Assets/Scenes/Stars.unity, Assets/Scripts/ConstellationDropdown.cs, Assets/Scripts/ConstellationDropdown.cs.meta, Assets/Scripts/DataController.cs, Assets/Scripts/StarComponent.cs, ProjectSettings/TagManager.asset
This PR does the following:
- adds a constellation highlight dropdown in the main star scene allowing users to highlight any of the constellations in the sphere
- restructure MainUI components to use Text mesh pro and have better organization
=> Add constellation highlight and restructure MainUI components

Assets/Materials/Marker_Mat.mat, Assets/Materials/Marker_Mat.mat.meta, Assets/Prefabs/Marker.prefab, Assets/Prefabs/Marker.prefab.meta, Assets/Scenes/Horizon.unity, Assets/Scenes/Planets.unity, Assets/Scenes/Stars.unity, Assets/Scripts/CelestialSphereManager.cs, Assets/Scripts/CelestialSphereManager.cs.meta, Assets/Scripts/Core/Star.cs, Assets/Scripts/DataController.cs, Assets/Scripts/FaceCamera.cs, Assets/Scripts/FaceCamera.cs.meta, Assets/Scripts/MarkerComponent.cs, Assets/Scripts/MarkerComponent.cs.meta
This PR adds markers to the celestial sphere.  Markers include the North and South celestial poles, a pole connector line, the vernal equinox, and an equator line.  These markers only appear in the `stars.unity` scene and can be toggled on and off from a checkbox in the UI controls.  Some refactoring and general UI clean-up is also included in this PR.  A few notes:
- I'm open to what the markers look like.  I used lineRenderers and simple spheres with a basic material and shader, but, again, I'm open to ideas on materials, shaders, sizes, colors, etc.  We'll probably need to look at things in the HoloLens and tweak based on what looks best (and get feedback from others).  The same goes for the text label associated with the markers.  I'm using a `FaceCamera` script to rotate the marker …
=> Celestial sphere markers

Assets/Scenes/Horizon.unity, Assets/Scripts/UIControlCamera.cs, Assets/Scripts/UIControlCamera.cs.meta
Somewhere along the line we broke the fps camera - which is probably fine since we are primarily targeting VR headsets with direct camera control, or WebGL where the complete capture of a mouse is a little obtrusive. I think this script, based on the buttons in the Stars scene implementation, may work better for WebGL builds but would welcome alternatives.
=> Simple camera controls in Horizon view

Assets/Scenes/Horizon.unity, Assets/Scripts/DataController.cs, Assets/Scripts/TextFromSlider.cs, Assets/Scripts/TextFromSlider.cs.meta
Allow user to specify year, day (1 to 365), hours, and minutes (0 to 24 as float) when in horizon view to update orientation of celestial sphere.  Checkbox toggle allows user to switch between current date-time and user specified date-time.  Values as human-readable string is also shown to user.  We eventually need tools to start/run a simulation and set the time period of the simulation.
=> Allow date and time of horizon view to be specified by user

Assets/Scripts/DataController.cs, Assets/Scripts/StarComponent.cs
Ahead of any refactoring, this will eliminate any null references tied to mouse events and star objects.  Scenes are designed to behave differently depending on whether or not certain game objects are present.  Changes add extra checks to ensure that we bypass functionality unless required game objects are present.
=> Add null reference protection

Assets/Prefabs/Star.prefab, Assets/Scripts/DataController.cs, Assets/Scripts/StarComponent.cs, Assets/Scripts/Utils.cs, Assets/Scripts/Utils.cs.meta
This small PR improves star rendering by using mesh vertex colors instead of changing material colors. Changing material colors creates individual instances of materials, which is very wasteful for our purposes. This technique saves over 500 draw calls since all stars now share a material.
Pre-tagged Star objects - we have a prefab for Stars, so easy to tag it before we add it to save some time.
Also added a new static Utils class with simple method to change object colors.
=> Improve star rendering

Assets/Scenes/Stars.unity, Assets/Scripts/StarComponent.cs
This PR changes the StarComponent interaction system to user PointerHandlers instead of MouseDown.  Only added to the Stars scene (Horizon scene needs updates to show constellations correctly):
- on pointer enter, adjust scale to highlight star
- on pointer exit, return to initial scale
- on pointer down, show star info panel and highlight constellation
- add physics raycaster to main camera
=> Use pointer down events to capture user interaction with stars

Assets/Scripts/MainUIController.cs, Assets/Scripts/SceneController.cs
A few small changes based on updates to the Vuforia fork.  These are all good protections to have in the main project to avoid future errors or exceptions.
- add protection around dataController in MainUIController in case object is null
- only skip 0th scene when user changes to prev/next scene if 0th scene is the LoadSim loading scene
=> Add protection around scene change and date/time updates in main UI

Assets/Scripts/Core/CelestialSphereItem.cs, Assets/Scripts/DataController.cs, Assets/Scripts/Utilities/Utils.cs
* Manually set time and automatic time star positions are in accordance, now both use `UtcNow`
* The Celestial Sphere had to be rotated 45 degrees.
* Rotational fraction of the planet is not quite 24 siderealHours hours. I am not sure if that is significant or not.
[#166009320]
https://www.pivotaltracker.com/story/show/166009320
=> Reorient celestial sphere. Sync times.

Assets/Scripts/Network/NetworkUI.cs, Assets/Scripts/SimulationManager.cs, Assets/Scripts/Utilities/SimulationConstants.cs
So this *almost* works see `PlayerLabelClicked` for the substance of it.
Seems like sometimes clicking on the label doesn't behave as it should.  It will load up the wrong location (The Location UI is incorrect).
I looked at the DataController, and noticed that is was setting nextLocation instead of location.  It seemed like I could trigger that with `PushPinSelected.Invoke(pin.Location, pin.SelectedDateTime)` but apparently not?
=> Click user label to visit pin

Assets/Prefabs/NetworkController.prefab, Assets/Scenes/Horizon.unity, Assets/Scenes/Stars.unity, Assets/Scripts/LocationPanel.cs, Assets/Scripts/Network/NetworkController.cs
Remove old sphere movement buttons and replace with the same controls as horizon view. Also made the location details hidden by default so we can use it for the test tomorrow (there's a hotkey to show them on desktop, but the VR user won't see them in the horizon).
Any other last-minute tweaks we can think of can go in this branch for the last-minute updates tomorrow.
=> Fixes for demo

Assets/Scenes/LoadSim.unity, Assets/Scripts/GroupSelectionWizard.cs, Assets/Scripts/UserRecord.cs, Assets/Scripts/Utilities/CCLogger.cs, Assets/Scripts/Utilities/SimulationConstants.cs
Makes several improvements / fixes in the Group Selection Wizard:
* Hides "Next" button from the last panel (scene selection).
* Checks UserPrefs for group and username info. Shows quick login button if those are good.
* Hides the username while selecting groups. (used to provide updating / changing username)
* Saves the users group preferences in UserPrefs.
=> LoadSim Shortcut to reload last user name & group

Assets/Scripts/Constellation.cs, Assets/Scripts/ConstellationsController.cs, Assets/Scripts/InteractionController.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/SimulationManager.cs, Assets/Scripts/SimulationManagerComponent.cs, Assets/Scripts/SnapshotsController.cs, Assets/Scripts/StarComponent.cs
Only show lines for single constellation selection in player color when a player is connected to the network - this is to differentiate between "who clicked that?".
=> Color lines by user color when selecting a constellation

Assets/Prefabs/MainUI.prefab, Assets/Prefabs/SnapItem.prefab, Assets/Scripts/Core/Pushpin.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/SnapshotsController.cs, Assets/Scripts/UI/SnapGrid.cs, Assets/Scripts/UI/SnapItem.cs, Assets/Scripts/Utilities/CCLogger.cs, Assets/Scripts/Utilities/TimeConverter.cs, ProjectSettings/GraphicsSettings.asset
Seems there's some object reference stickiness going on, so creating new pins to update the world seems to have fixed the issue for now. I had a lot of trouble removing items from the grid layout, so I wonder if similar issues persist in the network UI (hence our players leaving traces when they have disconnected).
=> Fix snapshot add overwriting other snap items in grid

Assets/Scripts/Network/PlayerMovement.cs
The log file analysis revealed that we were sending logging messages to our log server way too often on the Quest users in particular, since any head movement at all would trigger a pin update. I've added a threshold to the position deltas in an attempt to reduce the log bloat.
=> 171581766 Movement updates

Assets/Plugins/WebSocket/WebSocket.jslib
This PR fixes an issue in the Colyseus Javascript code that was checking against null and not undefined.  This caused an exception in the WebGL build when the user changed to another tab and then returned to CEASAR.
=> Fix websocket handling of undefined and null values

Assets/HTML.meta, Assets/HTML/index.html, Assets/HTML/index.html.meta, README.md
This PR adds an index.html file which can be used after the WebGL build process to overwrite the index.html file created by the Unity build.  The new index.html file included with the project contains additional CSS to more efficiently use the browser's vertical and horizontal space.  Additional build instructions have been added to the readme to clarify how to use this file during the build process.
=> Add pre-styled index.html file to use during build process and update readme

Assets/Scripts/UI/InfoPanelController.cs
This PR ensures that we use UTC 24 hour time when displaying times to the user in the information panel and in the snapshots.
=> Show crash site time in UTC 24

Assets/Scripts/UserRecord.cs
This PR fixes the handling of mapping user colors to text mesh colors.  Our code was failing in the WebGL version due to case sensitivity issues.  Remove the inconsistent `System.StringComparison.OrdinalIgnoreCase` and replace with a simple `toLower` on the user name string to ensure we find the proper color in the user name.
=> Fix handling of user colors to be more robust (was buggy in web version)

Assets/Scenes/Stars.unity, Assets/Scripts/UI/UIControlCamera.cs
This PR changes the functionality of the zoom in/out buttons in the celestial sphere scene.  Rather acting like a digital zoom and changing the camera field of view, we make the zoom act like a tracking shot and we move the camera in and out from the origin position.  This allows us to see outside the celestial sphere so users can have a better understanding of the celestial sphere concept.
=> Add ability to move in and out from celestial sphere using zoom

Assets/Scripts/Core/Pushpin.cs, Assets/Scripts/UI/InfoPanelController.cs
Add "UTC" to displayed time strings to help clarify the time system used in the application.
=> Add "UTC" to displayed time string

Assets/Scripts/UserRecord.cs
This PR fixes the handling of loading the previous login info in the WebGL version.  Our code was failing to load the previous login info in the WebGL version due to case sensitivity issues (similar to a previous issue that we had parsing these strings).  Remove the inconsistent `System.StringComparison.OrdinalIgnoreCase` and replace with a simple `toLower` to ensure string comparison behaves as expected.
=> Improve string handling when restoring previous login

Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/UI/MenuController.cs
Add the ability to rotate sphere up/down/left/right from the movement controls when in the celestial sphere scene.
=> Add ability to rotate sphere from movement control in sphere scene

Assets/Scenes/EarthInteraction.unity, Assets/Scenes/Horizon.unity, Assets/Scenes/Stars.unity
This PR double the thickness of the constellation lines so that they render better on a 2D screen (less gaps in lines at different distances and orientations).
=> Update the constellation line thickness

Assets/Scripts/AnnotationLine.cs
This PR changes the behavior when we click and hold to delete an annotation line.  Previously we used a particle effect, but we did not have an adequate shader to display this in different platforms (did not look correct in WebGL).  Instead we will replace this with a color change as the user clicks and holds.  The annotations will slowly become white and then will be deleted.
=> Use color change to indicate line deletion

Assets/Scripts/UI/UIControlCamera.cs
This PR sets limits to how far a user can look up or down with the camera in 2D versions of the app.  Previously a user could rotate the camera until they were effectively upside down and the horizon appeared at the top of the screen.  We will now limit the range so that the x rotation is between 270 and 90 degrees (look straight up, look straight down, and anything in between).
The behavior shown below was previously allowed and is now prevented:
=> Set camera rotation limits so that we do not turn the user upside down

Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/AnnotationLine.cs, Assets/Scripts/AnnotationTool.cs, Assets/Scripts/InteractionDetect.cs, Assets/Scripts/UI/MenuController.cs
This PR adds a handful of improvements to the line annotations.  Changes include:
- when using the annotation Undo button, turn on Show Annotations if it is off so users can see what is being removed.
- when adding annotations, don't add an annotation if the user clicks on something in the UI layer.  This was causing a strange bug where the user would press the Undo button to remove annotations, but if they were still in Draw mode, each Undo click was actually adding a new line annotation pt.  So every two times the user pressed Undo, a new line annotation was being created and hidden behind the undo button.
- show the line annotations by default when the Celestial Sphere scene is shown.
- hide all annotation buttons but show/hide in the Celestial Sphere scene.
- Fix some cases where the …
=> 179123376 annotation improvements

Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/UI/MenuController.cs, Assets/Scripts/UI/UIControlCamera.cs
This PR changes the sphere zoom so that we move the sphere itself rather than the camera.  This change has no effect on what the user sees, but is made in anticipation of adding the sphere zoom feature to the AR branch.  In the AR case we cannot move the camera since it is tied to the user headset position.  Instead, we need to move the sphere itself to achieve a zoom out/zoom in feature.
=> Update sphere zoom controls to move sphere instead of camera

Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/SimulationManagerComponent.cs, Assets/Scripts/UI/MenuController.cs
This PR adds a few small additions that were needed for the HL7 star scene.  These changes let us turn on/off the movement controls and set the rotation speed for the star scene.
=> Add ability to enable movement button and set rotation speed in MenuController

Assets/Scripts/UI/InfoPanelController.cs, Assets/Scripts/UI/MenuController.cs, Assets/Tests/TestMenuFunctions.cs
This PR fixes a bug where data/time changes were not being communicated to other users within the group.  If a user A changed the data/time and then user B chose to move to user A's location/date/time, user B would not have the latest date/time information to move to the correct sphere orientation.  This PR also removes some obsolete code that was causing confusion.
=> Communicate date/time changes to other users within the group

Assets/Prefabs/ConstellationConnection.prefab, Assets/Scripts/Constellation.cs, Assets/Scripts/ConstellationsController.cs, Assets/Scripts/StarComponent.cs, Assets/Scripts/UnusedCode/ConstellationDropdown.cs, Assets/Scripts/UnusedCode/StarInfoPanel.cs
This PR includes a handful of fixes to the constellation and star selection.  Changes include:
- Allow multiple constellations to be selected - one per each user.  Two users, A and B, can both select a unique constellation, this selection information will be communicated across the network, and both constellations will appear selected for both users.  This is now more in line with how the floating star panels work (each user can make a selection and other users can see it).
- Fix bug that caused constellation connection line colors to be incorrect (there was a shader bug that had been there for a while but it was magnified by the new colors).
- Fix bug that caused multiple clicks on stars to create multiple floating info panels.  Always destroy existing panel before making new one.
- …
=> Constellation and star selection fixes

Assets/Scenes/Stars.unity
Remove the VE, NCP, and SCP markers from the star scene.
=> Turn markers off in star scene

Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/UI/MenuController.cs
This PR makes changes so that the hide/show state of annotations persists between the horizon and the star scene.
=> Update annotation state when switching scenes

Assets/Prefabs/CelestialSphere.prefab, Assets/Prefabs/Interactions/AnnotationLineRender.prefab, Assets/Prefabs/Interactions/AnnotationLineRender.prefab.meta, Assets/Scenes/EarthInteraction.unity, Assets/Scenes/Horizon.unity, Assets/Scenes/Stars.unity, Assets/Scripts/AnnotationLine.cs, Assets/Scripts/AnnotationTool.cs, Assets/Scripts/Core/SimulationEvents.cs, Assets/Scripts/Network/ColyseusClient.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/SimulationManagerComponent.cs, Assets/Scripts/Utilities/CCLogger.cs
This PR updates the annotation lines to use curved line renderers that follow the path of the celestial sphere rather than using a straight line that is scaled from the center point (which causes a "toothpick" effect when viewed in the star scene.  A slerp function is used to create 30 line segments along the arc of the celestial sphere given a start point and an end point defined by the user.
Note: network communication will ideally be cleaned up when more development time opens up.  Ideally we want a new network type/class for passing annotation information, but the current code gets the job done for now.
Note2: additional features to set a line width multiplier and scale the annotation tool game object are in place to facilitate changes needed for the HoloLens version.
=> Curved annotations

Assets/Scripts/AnnotationTool.cs, Assets/Scripts/SimulationManagerComponent.cs
This PR includes a new scaleFactor variable that is added to the annotation tool so that we can guarantee that annotations created at non-1;1 scales can be sent over the network at a 1:1 scale.  This has no effect on the web version, but it needed in the HL2 version where the sphere is not at a 100% zoom and hence annotations need to be manipulated before being sent over the network.
=> Updates to help sync annotations

Assets/Prefabs/UI/FloatingInfoPanel.prefab
This is a small PR that updates the star panel prefab so that the text box text size will shrink to accommodate large strings (using the autoSizing property).  This prevents text from overflowing off of the star panel.
PT Story:
https://www.pivotaltracker.com/story/show/179381008
=> Adjust text size in floating panel to fit content (179381008)

Assets/Scripts/AnnotationTool.cs, Assets/Scripts/Core/SimulationEvents.cs, Assets/Scripts/Network/ColyseusClient.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Utilities/CCLogger.cs
This PR makes improvements to the network communication of annotations so that annotations are correctly placed regardless of the user's current time and location.  This is done by passing an additional rotation value that is used to compute annotation positions.
NOTE: to do this properly we will likely want to change the network at some point to support a new annotation type where we can send start position, end position, and rotation.  At present I'm using an existing network type, `NetworkTransform`, that works but isn't designed for the annotation data.  In both cases we need to send 3 Vector3 objects, but the `NetworkTransform` and `NetworkAnnotation` (a proposed new type) will need different naming conventions for properties.  I'm voting that we put this off until we have time to …
=> Add rotation to annotation network communication to sync annotation positions (179381096)

Assets/Scripts/Network/ServerList.cs, Assets/Scripts/Utilities/SimulationConstants.cs
Otherwise we get mixed-content security warnings when the application loads over HTTP.
=> 2022-01-25 - Use SSL for Websocket & Log Server connections
