concord-consortium/CEASAR

Assets/Materials/Earth.mat, Assets/Materials/Moon.mat, Assets/Prefabs/Earth.prefab, Assets/Prefabs/Moon.prefab, Assets/Prefabs/Star.prefab, Assets/Scenes/Planets.unity, Assets/Scripts/DataController.cs, Assets/Scripts/Orbit.cs, Assets/Scripts/Orbit.cs.meta, Assets/Scripts/Rotate.cs, Assets/Scripts/Rotate.cs.meta, Assets/Scripts/SimpleCameraFollow.cs, Assets/Scripts/SimpleCameraFollow.cs.meta, Assets/Scripts/Sunlight.cs, Assets/Scripts/Sunlight.cs.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200401.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200402.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200403.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200404.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200405.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200406.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200407.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200408.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200409.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200410.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200411.3x5400x2700.png.meta, Assets/Textures/PlanetaryBodies/Earth/world.topo.bathy.200412.3x5400x2700.png.meta, ProjectSettings/TagManager.asset
Change to all-in-one textures for Earth model, add simple planetary rotation and orbit scripts. These are not accurate calculations, and the sizes and positions of each body are not to scale.
=> Update Planet scene

Assets/Prefabs/SceneSelectionPanel.prefab, Assets/Prefabs/SceneSelectionPanel.prefab.meta, Assets/Scenes/Horizon.unity, Assets/Scenes/Planets.unity, Assets/Scenes/Stars.unity, Assets/Scripts/SceneController.cs, Assets/Scripts/SceneController.cs.meta, ProjectSettings/EditorBuildSettings.asset
Build simple UI buttons to move to the previous or next scene in the build settings.  Can also be controlled with shortcut keys (left arrow or 4 for previous scene, right arrow or 6 for next scene).
=> Scene change

Assets/Scenes/Horizon.unity
Quick change to FPS controller to allow buttons to work in horizon view.
=> Remove lock cursor in horizon scene to allow scene transition buttons to function

Assets/Scenes/Horizon.unity, Assets/Scripts/DataController.cs, Assets/Scripts/SunPosition.cs
Small changes to improve functionality of the data/time selection in the Horizon view.
- current date time is displayed in UTC
- user defined time is used for sun position
- fix bug causing sun arc creation failure when changing city
- minor UI positioning
=> Date time updates

Assets/Prefabs/Star.prefab, Assets/Scenes/Stars.unity, Assets/Scripts/ConstellationDropdown.cs, Assets/Scripts/DataController.cs, Assets/Scripts/StarComponent.cs, Assets/Scripts/StarInfoPanel.cs, Assets/Scripts/StarInfoPanel.cs.meta, Assets/Scripts/WorldToScreenPos.cs, Assets/Scripts/WorldToScreenPos.cs.meta
This PR implements additional star interactions including:
- user can click on star to highlight constellation that it is a part of
- user can hover over a star to see an info popup about the star (this can be turned on or off from a checkbox in the UI control panel)
=> Star selection

Assets/Materials/Marker_Mat.mat, Assets/Scenes/Stars.unity, Assets/Scripts/DataController.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/MarkersController.cs, Assets/Scripts/MarkersController.cs.meta
Small fix to marker material and refactor to:
- add MarkersController script to handle creation of markers
- remove marker references from DataController (move to MarkersController)
- remove other UI component references from DataController and move to MainUIController
=> Marker refactor

Assets/Prefabs/Constellation.prefab, Assets/Prefabs/ConstellationLine.prefab, Assets/Prefabs/ConstellationLine.prefab.meta, Assets/Prefabs/Star.prefab, Assets/Scenes/EarthInteraction.unity, Assets/Scenes/Horizon.unity, Assets/Scenes/Planets.unity, Assets/Scenes/Stars.unity, Assets/Scripts/Constellation.cs, Assets/Scripts/ConstellationsController.cs, Assets/Scripts/Core/Star.cs, Assets/Scripts/DataController.cs, Assets/Scripts/StarComponent.cs, Assets/Scripts/Utils.cs, ProjectSettings/TagManager.asset
As part of the work on updating positions via a rotation of the celestial sphere, I started refactoring some items. As such, I figured getting these changes in early would smooth out the process! The rotation parts will come in a later PR.
=> Star constellation refactor

Assets/Scenes/LoadSim.unity, Assets/Scripts/MarkersController.cs, Logs/Packages-Update.log, Packages/manifest.json, ProjectSettings/ProjectVersion.txt
Upgrade to 2019.1.7f1
Update LoadSim scene to use the Stars skybox and add a panel in the center
=> Update Unity and update Intro scene

Assets/Scripts/MainUIController.cs, Assets/Scripts/MarkersController.cs
Adjustments to the scaling when creating markers
=> Fix marker line width

Assets/Scenes/LoadSim.unity, ProjectSettings/EditorBuildSettings.asset
Removes the scene from the list of scenes to include in a build. Scene still exists in project, but we're not using it currently, so this just hides it. 
Also adjusted the button sizes on the main menu to be more easily clickable on smaller displays
=> Removed the Planet scene

Assets/Models/star3d.obj.meta, Assets/Prefabs/Avatar.prefab, Assets/Prefabs/NetworkController.prefab, Assets/Scenes/EarthInteraction.unity, Assets/Scripts/Network/ColyseusClient.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Network/PlayerMovement.cs, Assets/Scripts/Network/PlayerMovement.cs.meta, Assets/Scripts/Network/RemotePlayerMovement.cs, Assets/Scripts/Network/RemotePlayerMovement.cs.meta, Assets/Scripts/SimulationManager.cs
Handle updates in user position (relative to main camera) and relay across the network to see all users at the correct locations. While we are not yet sending movement information directly from user input from clients, this framework enables the remote movement and network communication, and can be tested in-editor for now. 
Requires changes in https://github.com/concord-consortium/CEASAR-server/pull/4
=> Movement updates

Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Utilities/CCLogger.cs, Assets/Scripts/Utilities/CCLogger.cs.meta
This PR should be reviewed after #58 
Commit 3853715 here is from #58 (this PR is ontop of that one)
This does the basics to complete basic logging as per:
[#170060407]
https://www.pivotaltracker.com/story/show/170060407
Here is the log its producing in the CC Log Manager:
```
[ 
{ 
"id":196158369,
"session":null,
"username":null,
"application":"CEASAR",
"activity":"activity",
"event":null,
"time":"2019-12-20T22:53:48.000Z",
"parameters":{ 
},
"extras":{ 
"scene":"scene",
"message":"",
"userName":"",
"event_name":"Connect",
"platformName":"OSXPlayer"
},
"event_value":"Connect",
"run_remote_endpoint":null
},
{ 
"id":196158368,
"session":null,
"username":null,
"application":"CEASAR",
"activity":"activity",
"event":null,
"time":"2019-12-20T22:53:48.000Z",
"parameters":{ 
},
"extras":{ …
```
=> 170060407 add logging

Assets/Scripts/SceneLoader.cs
Also adjust UI height upwards to ensure lower portion is still visible on Horizon view
=> Improve switching cameras for platforms that have a VR device attached

Assets/Prefabs/VRPointer.prefab, Assets/Scripts/StarComponent.cs, Assets/Scripts/VR/VRInteraction.cs
Interaction with the stars will now work via the Quest controllers, same as interaction with Earth. Networking of star and constellation information is separate from this task, and involves schema changes to enable the remote clients to see the desired selection changes.
=> Make the laser reach the stars, enable selection

Assets/Materials/Earth_new.mat, Assets/Plugins/Editor.meta, Assets/Prefabs/Earth.prefab, Assets/Prefabs/InteractionController.prefab, Assets/Prefabs/InteractionController.prefab.meta, Assets/Prefabs/SimManager.prefab, Assets/Scenes/EarthInteraction.unity, Assets/Scripts/InteractionController.cs, Assets/Scripts/InteractionController.cs.meta, Assets/Scripts/InteractionDetect.cs, Assets/Scripts/Network/ColyseusClient.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Network/PlayerMovement.cs, Assets/Scripts/SimulationManager.cs, Assets/Scripts/SimulationManagerComponent.cs, Assets/Scripts/StarComponent.cs, Assets/Scripts/Utilities/Utils.cs, Assets/Scripts/VR/VRInteraction.cs, Assets/StreamingAssets.meta, Assets/SunCalcNet/SunCalcNet.csproj.meta, ProjectSettings/TagManager.asset
Still more to do on this honestly (like add the Lat/Lng to the location panel)
Actually the bulk of this work was just pulling out the InteractionController ...
=> Find Lat/Lng of EarthInteraction points.  

Assets/Prefabs/MainUI.prefab, Assets/Scripts/InteractionController.cs, Assets/Scripts/LocationPanel.cs, Assets/Scripts/LocationPanel.cs.meta
Just have a look @dstrawberrygirl -- This is just an experiment.
Super easy to setup actually, as you were saying.
=> Interaction event testing

Assets/Prefabs/SimManager.prefab, Assets/Scenes/EarthInteraction.unity, Assets/Scripts/DataController.cs, Assets/Scripts/Interactions.meta, Assets/Scripts/LocationPanel.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/SimulationManagerComponent.cs, Assets/Scripts/StarComponent.cs
Also allow for different materials for stars in each scene
Merge after https://github.com/concord-consortium/CEASAR/pull/71 is approved
=> Fix star size when switching scenes / interacting

Assets/Materials/AnnotationLine.mat, Assets/Materials/AnnotationLine.mat.meta, Assets/Materials/AnnotationLineHighlight.mat, Assets/Materials/AnnotationLineHighlight.mat.meta, Assets/Models/Icosphere.obj.meta, Assets/Prefabs/CelestialSphere.prefab, Assets/Prefabs/Interactions/AnnotationLineHighlight.prefab, Assets/Prefabs/Interactions/AnnotationLineHighlight.prefab.meta, Assets/Prefabs/Interactions/AnnotationTool.prefab, Assets/Scenes/Horizon.unity, Assets/Scenes/Stars.unity, Assets/Scripts/AnnotationTool.cs, Assets/Scripts/ConstellationsController.cs, Assets/Scripts/DataController.cs, Assets/Scripts/InteractionDetect.cs, Assets/Scripts/StarComponent.cs
Fix some issues with drawing annotations and add some new features, including:
- Annotations now attach to the sphere and move with the celestial sphere.
- Annotations have a small highlight that matches the player's color
- Removed Icosphere for mouse click detection - not needed, thanks math!
=> 170561517 improve annotations

Assets/Prefabs/MainUI.prefab, Assets/Prefabs/smallOrangeButton.prefab, Assets/Prefabs/smallOrangeButton.prefab.meta, Assets/Resources/animals-new.txt, Assets/Resources/animals-new.txt.meta, Assets/Resources/colors-new.txt, Assets/Resources/colors-new.txt.meta, Assets/Scenes/LoadSim.unity, Assets/Scripts/AnnotationTool.cs, Assets/Scripts/GroupSelectionWizard.cs, Assets/Scripts/GroupSelectionWizard.cs.meta, Assets/Scripts/InteractionController.cs, Assets/Scripts/Network/ColyseusClient.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Network/NetworkUI.cs, Assets/Scripts/Network/ServerList.cs, Assets/Scripts/Network/ServerList.cs.meta, Assets/Scripts/SimulationManager.cs, Assets/Scripts/UserRecord.cs, Assets/Scripts/UserRecord.cs.meta, Assets/Scripts/Utilities/CCLogger.cs
So this is sort of work in progress, but it does seem to work when used with the [server changes](https://github.com/concord-consortium/CEASAR-server/pull/8) .
[#170409570]
https://www.pivotaltracker.com/story/show/170409570
=> Initial spike: Different Colyseus room names

Assets/Scripts/Core/Pushpin.cs, Assets/Scripts/Core/SimulationEvents.cs, Assets/Scripts/DataController.cs, Assets/Scripts/InteractionController.cs, Assets/Scripts/InteractionDetect.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/PushpinComponent.cs, Assets/Scripts/SimulationManager.cs, Assets/Scripts/SnapshotsController.cs, Assets/Scripts/Utilities/SimulationConstants.cs, Assets/Scripts/VR/VRInteraction.cs
Lots of fixes for date and time by telling the UI not to update the date and time when showing the currently-set date and time.
=> 170977509 fix datetime pins

Assets/Scripts/SceneController.cs, Assets/Scripts/Utilities/SimulationConstants.cs
Simplified Scene loader ... Not urgent. Just putting this PR in because its atomic.
=> Simplified scene switching in SceneController

Assets/Scenes/LoadSim.unity, Assets/Scripts/MainUIController.cs, Assets/Scripts/Network/NetworkUI.cs, Assets/Scripts/SceneController.cs
Wow this was tiny! 😀
eea2981 is where the fix is.
6c204ec and 06b7f03  were just minor tweaks
=> Fix Scene navigation buttons

Assets/Scripts/Core/Pushpin.cs, Assets/Scripts/InteractionController.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Network/PlayerMovement.cs, Assets/Scripts/Utilities/CCLogger.cs, Assets/Scripts/Utilities/SimulationConstants.cs, Assets/Scripts/Utilities/Utils.cs
* Removed useless helper class "context" and made that all part of the logger itself.
* Added more serialized fields for logging context (lastPosition, lastHeading, selectedStar) &etc.
* Light wrapper around events
[#170563535] Add More logging
https://www.pivotaltracker.com/story/show/170563535
=> Start listening to more Events. Log more location information.

Assets/Scripts/InteractionController.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/RotateFaceCamera.cs, Assets/Scripts/SceneLoader.cs, Assets/Scripts/VR/VRInteraction.cs, ProjectSettings/GraphicsSettings.asset, ProjectSettings/QualitySettings.asset
Compiling for WebGL requires deleting the Oculus folder due to issues with non-existent microphones. These small changes mean that deleting that folder is all that is required to produce a web build
=> WebGL changes

Assets/Scripts/ConstellationsController.cs, Assets/Scripts/Core/CelestialSphereItem.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/StarInfoPanel.cs, Assets/Scripts/Utilities/Utils.cs
Clearing star selection on scene change, adding in Alt / Az for the selected star in the panel. 
This PR follows https://github.com/concord-consortium/CEASAR/pull/97
=> Add Altitude and Azimuth for selected stars

Assets/Scripts/ConstellationsController.cs, Assets/Scripts/Core/CelestialSphereItem.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/StarInfoPanel.cs, Assets/Scripts/UI/SnapGrid.cs, Assets/Scripts/Utilities/Utils.cs
Merged the previous PR into the wrong branch
=> Snapshot add delete

Assets/Scripts/Core/SimulationEvents.cs, Assets/Scripts/DataController.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/StarInfoPanel.cs
Two small fixes in here - one to get the time sliders and star panel to update whenever the time changes (and also if you have clicked the Run button), and the other main change is to include the longitude in the sidereal time calculation for alt/az.
=> Fix Alt/Az to include longitude calculation

Assets/Prefabs/MainUI.prefab, Assets/Prefabs/NetworkController.prefab, Assets/Scripts/Network/ColyseusClient.cs, Assets/Scripts/Network/NetworkController.cs, Assets/Scripts/Network/NetworkUI.cs
Fix network connection so we can now capture exceptions on login due to non-existent servers. 
Re-enable auto-connect
Remove Dev and Local unless a checkbox is set locally
=> 171439903 network connection

Assets/Prefabs/MainUI.prefab, Assets/Scenes/LoadSim.unity, Assets/Scripts/GroupSelectionWizard.cs, Assets/Scripts/SceneController.cs, Assets/Scripts/Utilities/SimulationConstants.cs, Assets/Scripts/VR/VRInteraction.cs, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/TagManager.asset
Disable the Stars scene on the Quest - we have had too many users complain of feeling dizzy in that mode in VR.
=> Quest disable stars scene

Assets/Scripts/Core/SimulationEvents.cs, Assets/Scripts/MainUIController.cs, Assets/Scripts/SimulationManager.cs, Assets/Scripts/Utilities/CCLogger.cs, Assets/Scripts/Utilities/SimulationConstants.cs
Added an event that fires whenever the user positions the pin, and added a listener in the logging section to send the message to the log server.
=> Log the event of dropping the North Pin

ProjectSettings/GraphicsSettings.asset, ProjectSettings/ProjectSettings.asset, README.md
I've added a lot of information to the ReadMe - let me know if there are any areas that need more detail!
=> Updating documentation

README.md
Update the readme to include build steps.  This specifically updates the HoloLens section to document the lengthy HoloLens setup and process.
=> Update readme with build steps

Assets/Prefabs/UI/InformationPanel.prefab, Assets/Scripts/UI/InfoPanelController.cs
Add Right ascension, declination, and distance in light years to the information panel.
=> Add RA, Dec, and Dist to information panel

Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/UI/MenuController.cs
This PR adds minute increment and decrement to the time tools.  Note that this is not the final UI.  Michael is working on revising some of the menus so icons, positioning, etc. might change.  However, for this story we just wanted to get the functionality in place so we can see if the feature behaves well.
=> Add minute increment and decrement to time tools

Assets/Prefabs/Moon.prefab, Assets/Prefabs/Sun.prefab, Assets/Scripts/Core/SimulationEvents.cs, Assets/Scripts/DataController.cs, Assets/Scripts/MoonComponent.cs, Assets/Scripts/MoonComponent.cs.meta, Assets/Scripts/StarComponent.cs, Assets/Scripts/SunComponent.cs, Assets/Scripts/SunComponent.cs.meta, Assets/Scripts/UI/InfoPanelController.cs, Assets/Scripts/UI/MenuController.cs
This PR makes the sun and moon selectable.  When selected, their Alt-Az values appear in the information panel.  Changes include:
- Add `MoonComponent` and `SunComponent` classes to handle interaction with moon and sun
- Add `SunSelected` and `MoonSelected` events that are used to send selection information to other components
- Update the `InfoPanelController` to update when moon or sun are selected, keep track of selected object, and update sun/moon info when time based events are fired.
=> 179027435 select sun moon

Assets/Data/worldcities-lat-log-zones.txt, Assets/Prefabs/UI/InteractionMenu.prefab, Assets/Scripts/GroupSelectionWizard.cs
This PR changes the initial location and position when loading the app.  Rather than using the crash site, we will now use Champaign, Illinois at the current time.  This is the first location/time that is used for loading the Horizon scene when the user enters the app.
=> Set the initial location to Champaign, IL and the time to current time

Assets/Scripts/MoonComponent.cs, Assets/Scripts/StarComponent.cs, Assets/Scripts/SunComponent.cs
This PR includes small improvements to the creation and deletion of the floating star info panel.  Changes include:
- refine function that handles star selection, add handling for case where a star is selected by choosing a constellation
- add extra null checking around deletion of floating star info panel.
- remove function that handles sun selection inside sun component and moon selection inside moon component.  This is handled directly by the click handler and these cases were superfluous and confusing.
- minor refactor to reduce reused code
=> Improve handling of floating info panel, add when star is selected via constellation

Assets/Resources/animals-new.txt, Assets/Scripts/GroupSelectionWizard.cs
This PR makes small improvements to the login screen to improve readability and accessibility.  Changes include:
- update animal names to shorter strings that fit better in space
- improve login color selection button visibility
- improve strings that indicate steps as user creates id
=> 179291540 login updates
